### ISSUE TITLE
Issues acquiring token interactively

### ISSUE THREAD

**Issue by paulpopiel** [Francessco121/msal-js-dart#23]
**Describe the bug**
When needing to acquire a token interactively, we are facing the issue that:
- If you use the redirect method, the subsequent `acquireTokenSilent` fails due to most browsers blocking third-party cookies now. This then follows up with another redirect token request, and you fall into an infinite loop.
- If you use the popup method, most browsers block popups these days. So that fails. 

Basically after the initial token expires, there is no way to get a new one. 

**To reproduce**
Basic get token code:
```
    if (_msalUserAgentApp.getAccount() == null) {
      throw Exception('Should not attempt to get token if not logged in');
    }

    final tokenRequest = new AuthRequest()..scopes = scopes;
    try {
      final response = await _msalUserAgentApp.acquireTokenSilent(tokenRequest);
      return response.accessToken;
    } on InteractionRequiredAuthException {
      final response = await _msalUserAgentApp.acquireTokenPopup(tokenRequest);
      return response.accessToken;
    } catch (e) {
      throw e;
    }
```

Looking for some guidance as to workarounds if there are any?
All threads related to similar issues posted on the MSAL git pages and elsewhere seem to all suggest moving to MSAL 2.0.
However this package, nor any others, seem to support this.

**Environment (please complete the following information):**
 - Flutter: yes
 - Browser: safari, chrome
 - Dart msal_js Version: 1.3.0
 - JavaScript msal.js Version: 1.3.1

**Comment by Francessco121** [comment]
This is a much better question for the MSAL devs over at https://github.com/AzureAD/microsoft-authentication-library-for-js. Unfortunately, I don't know enough about how MSAL works under the hood to answer this, this is just a Dart wrapper.

If the only real solution here is to use MSAL 2.x then this package can't help you (yet). I would like to support MSAL 2 in the future.

**Comment by paulpopiel** [comment]
@Francessco121 no worries, thanks for the reply.

One quick question if you don't mind me asking:

I am trying to write my own wrapper for MSAL 2.x but noticing that the latest versions dont have any exports / are not a module.

As such I am hitting a blocker as I don't know how to interop into it.

i.e. 
```
@JS('???')
library interop;
```

using `Msal` does not work obviously.

Using the following:
```
  <script
          type="text/javascript"
          src="https://alcdn.msauth.net/browser/2.12.1/js/msal-browser.js"
          integrity="sha384-QMpSjAFJzgh/J1zBL23Xx95KfVI1n9Je9GmB3byJbZ0/hj8o9CJTmxOK/BPZivil"
          crossorigin="anonymous"></script>
```

If you have the time to provide any guidance or possible insights into this it would be much appreciated.
Pretty much written most of the wrappers for all the classes, so this is the only thing blocking me at the moment :(
