### ISSUE TITLE
How to get accessToken

### ISSUE THREAD

**Issue by pavane90** [Francessco121/msal-js-dart#24]
Hello
I have a rudimentary knowledge of MSAL and Azure AD B2C.

Login successfully using this plug-in and id_token was verified. 
However, if I try to check accessToken, NULL will be returned.
(ex : print('accessToken : ${response.accessToken}');)

Using AcquireTokenRedirect() or AcquireTokenSilent() seems like I can get accessToken. But I don't know how to use it. :$

This is my code made using the [Flutter Web example.](https://github.com/Francessco121/msal-js-dart/blob/master/example/flutter_web_example.md)

Finally, I want to update accesstoken to getx → When I request API, I want to include accessToken in the header.

```dart
import 'package:xxxxxx/binding/init_binding.dart';
import 'package:xxxxxx/pages/desktop_home.dart';
import 'package:xxxxxx/pages/mobile_home.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:get/get.dart';
import 'package:msal_js/msal_js.dart';
import 'package:xxxxxx/common/common.dart';

void main() {
  // Create an MSAL UserAgentApplication
  final userAgentApplication = UserAgentApplication(
    Configuration()
      ..auth = (AuthOptions()
        ..clientId = clientId
        ..authority = authority
        ..validateAuthority = false
        ..knownAuthorities = [knownAuthorities]
        ..redirectUri = redirectUri),
  );
  userAgentApplication.handleRedirectCallback(_redirectCallback);

  runApp(MyApp(
    userAgentApplication: userAgentApplication,
  ));
}

void _redirectCallback(AuthException? error, [AuthResponse? response]) {
  if (error != null) {
    // Redirect login failed
    print('MSAL: ${error.errorCode}:${error.errorMessage}');
  } else {
    // Redirect login succeeded
    print('Redirect login successful. name: ${response!.account!.name}');
    print('tokenType : ${response.tokenType}');
    print('accessToken : ${response.accessToken}');
    print('idToken : ${response.idToken}');
    print('accountState : ${response.accountState}');
    print('expiresOn : ${response.expiresOn}');
    print('tenantId : ${response.tenantId}');
    print('uniqueId : ${response.uniqueId}');
  }
}

class MyApp extends StatelessWidget {
  final UserAgentApplication userAgentApplication;

  MyApp({required this.userAgentApplication});
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter2',
      theme: ThemeData(
        primaryColor: Colors.grey,
        appBarTheme: AppBarTheme(color: Colors.grey),
      ),
      home: MyHomePage(userAgentApplication: userAgentApplication),
      initialBinding: InitBinding(),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
    );
  }
}

class MyHomePage extends StatefulWidget {
  final UserAgentApplication userAgentApplication;

  MyHomePage({
    required this.userAgentApplication,
    Key? key,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Account? _account;

  @override
  void initState() {
    super.initState();

    _account = widget.userAgentApplication.getAccount();
  }

  void _loginRedirect() {
    widget.userAgentApplication.loginRedirect(AuthRequest()..scopes = scopes);
  }

  void _logout() {
    widget.userAgentApplication.logout();
  }

  @override
  Widget build(BuildContext context) {
    if (_account == null) {
      _loginRedirect();
      return Scaffold(
        appBar: AppBar(
          title: Text('Flutter2'),
        ),
        body: Center(
          child: CircularProgressIndicator(),
        ),
      );
    } else {
      return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
          if (constraints.maxWidth > 600) {
            return DesktopHome();
          } else {
            return MobileHome();
          }
        },
      );
    }
  }
}

```

**Comment by Francessco121** [comment]
Sounds like you're not passing a scope for a resource that would generate an access token. For example, if you want an access token for your own API, you need to create a scope for that API and then pass it to `login` or `acquireToken`. Without this, MSAL will only return an ID token.

> When I request API, I want to include accessToken in the header.

This depends on the API, but usually you just include the access token in the `Authorization` header as a `Bearer` token.

**Comment by pavane90** [comment]
Thank you for helping me.
I made scopes as below and redirected it to jwt.ms.
(The scope named 'access_user' was created in Azure)

However, the result of scp does not show access_user :$
What am I doing wrong?
final List<String> scopes = ["https://<tenentID>.onmicrosoft.com/api/access_user"]

P.S - scopes does not contain openid and profile, but the generated URL contains it. Can't you get rid of it?

**Comment by Francessco121** [comment]
Hmm, it's kind of hard to say without knowing your setup. B2C in particular has a bunch of pitfalls.

You'll probably want to go through the B2C setup articles for MSAL and see if you missed anything. Seeing how this isn't a Dart issue, you may also want to consider asking for help over at https://github.com/AzureAD/microsoft-authentication-library-for-js. The developers there can provide much better help than I can.

> P.S - scopes does not contain openid and profile, but the generated URL contains it. Can't you get rid of it?

Nope, MSAL adds those because they are required for MSAL to function. The `openid` scope is needed because MSAL implements OpenID connect for auth and `profile` is needed to get an ID token at all, which I believe is also used internally.

**Comment by pavane90** [comment]
I'm not sure, but I don't think it's a dart problem. 
I feel like I'm letting go of something.

Am I getting it right?

request id_token to Azure AD B2C using MSAL.JS -> request access token using corresponding id_token and scopes

**Comment by Francessco121** [comment]
Almost, you don't request an access token using an ID token. You get both tokens by using the `login` methods and access tokens from the `acquire` methods by passing requested scopes needed in the token.

I could be missing something, I'm certainly no expert on Azure AD.

**Comment by pavane90** [comment]
Thank you for your answers.    It was very helpful to me.

**Comment by Francessco121** [comment]
Were you able to solve the issue?

**Comment by pavane90** [comment]
Unfortunately, I haven't solved it yet.
Thank you.
